src/Entity/Answers.php
<?php

namespace App\Entity;

use App\Repository\AnswersRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AnswersRepository::class)
 */
class Answers
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $content;

    /**
     * @ORM\Column(type="integer")
     */
    private $vote_count;

    /**
     * @ORM\ManyToOne(targetEntity=Poll::class, inversedBy="answer")
     * @ORM\JoinColumn(nullable=false)
     */
    private $poll;

    /**
     * @ORM\OneToMany(targetEntity=Vote::class, mappedBy="answers")
     */
    private $votes;

    public function __construct()
    {
        return $this->vote_count=0;
        $this->votes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getVoteCount(): ?int
    {
        return $this->vote_count;
    }

    public function setVoteCount(int $vote_count): self
    {
        $this->vote_count = $vote_count;

        return $this;
    }

    public function getPoll(): ?Poll
    {
        return $this->poll;
    }

    public function setPoll(?Poll $poll): self
    {
        $this->poll = $poll;

        return $this;
    }

    /**
     * @return Collection|Vote[]
     */
    public function getVotes(): Collection
    {
        return $this->votes;
    }

    public function addVote(Vote $vote): self
    {
        if (!$this->votes->contains($vote)) {
            $this->votes[] = $vote;
            $vote->setAnswers($this);
        }

        return $this;
    }

    public function removeVote(Vote $vote): self
    {
        if ($this->votes->contains($vote)) {
            $this->votes->removeElement($vote);
            // set the owning side to null (unless already changed)
            if ($vote->getAnswers() === $this) {
                $vote->setAnswers(null);
            }
        }

        return $this;
    }
}

src/Entity/Poll.php
<?php

namespace App\Entity;

use App\Repository\PollRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PollRepository::class)
 */
class Poll
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="boolean")
     */
    private $multiple_choice;

    /**
     * @ORM\Column(type="boolean")
     */
    private $draft;

    /**
     * @ORM\OneToMany(targetEntity=Answers::class, mappedBy="poll", orphanRemoval=true, cascade={"persist"})
     */
    private $answer;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    /**
     * @ORM\OneToMany(targetEntity=Vote::class, mappedBy="poll")
     */
    private $votes;

    public function __toString()
    {
        return (string) $this->getId();
    }

    public function __construct()
    {
        $this->answer = new ArrayCollection();
        $this->date = new \DateTime();
        $this->votes = new ArrayCollection();
        $this->draft = 0;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getMultipleChoice(): ?bool
    {
        return $this->multiple_choice;
    }

    public function setMultipleChoice(bool $multiple_choice): self
    {
        $this->multiple_choice = $multiple_choice;

        return $this;
    }

    public function getDraft(): ?bool
    {
        return $this->draft;
    }

    public function setDraft(bool $draft): self
    {
        $this->draft = $draft;

        return $this;
    }

    /**
     * @return Collection|Answers[]
     */
    public function getAnswer(): Collection
    {
        return $this->answer;
    }

    public function addAnswer(Answers $answer): self
    {
        if (!$this->answer->contains($answer)) {
            $this->answer[] = $answer;
            $answer->setPoll($this);
        }

        return $this;
    }

    public function removeAnswer(Answers $answer): self
    {
        if ($this->answer->contains($answer)) {
            $this->answer->removeElement($answer);
            // set the owning side to null (unless already changed)
            if ($answer->getPoll() === $this) {
                $answer->setPoll(null);
            }
        }

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    /**
     * @return Collection|Vote[]
     */
    public function getVotes(): Collection
    {
        return $this->votes;
    }

    public function addVote(Vote $vote): self
    {
        if (!$this->votes->contains($vote)) {
            $this->votes[] = $vote;
            $vote->setPoll($this);
        }

        return $this;
    }

    public function removeVote(Vote $vote): self
    {
        if ($this->votes->contains($vote)) {
            $this->votes->removeElement($vote);
            // set the owning side to null (unless already changed)
            if ($vote->getPoll() === $this) {
                $vote->setPoll(null);
            }
        }

        return $this;
    }
}

src/Form/PollType.php
<?php

namespace App\Form;

use App\Entity\Poll;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PollType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', TextType::class, [
                'label' => 'create.title',
                'label_attr' => [
                    'class' => 'title-label'
                ],
                'attr' => [
                    'placeholder' => 'create.typeYouQuestionHere',
                    'class' => 'title-input'
                ]
            ])
            ->add('answer', CollectionType::class, [
                'entry_type' => AnswerType::class,
                'allow_add' => true,
                'by_reference' => false,
                'allow_delete' => true,
                'label' => 'Questions',
                'label_attr' => [
                    'class' => 'answer-label'
                ],
                'entry_options' => [
                    'label' => false,
                ],
            ])
            ->add('multiple_choice', CheckboxType::class, [
                'label' => 'create.multiple_choice',
                'required' => false
            ])
//            ->add('draft', CheckboxType::class, [
//                'label' => 'create.draft',
//                'required' => false
//            ]);
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Poll::class,
        ]);
    }
}

src/Controller/PollController.php
<?php

namespace App\Controller;

use App\Entity\Answers;
use App\Entity\Poll;
use App\Form\PollType;
use App\Form\VoteType;
use App\Repository\AnswersRepository;
use App\Repository\PollRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Psr\Log\LoggerInterface;

/**
 * @Route("/")
 */
class PollController extends AbstractController
{

    /**
     * @Route("/", name="poll_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $poll = new Poll();
        $form = $this->createForm(PollType::class, $poll);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($poll);
            $entityManager->flush();

            return $this->redirectToRoute('poll_vote', [
                'id' => $poll->getId()
            ]);
        }

        return $this->render('poll/new.html.twig', [
            'poll' => $poll,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="poll_vote", methods={"GET", "POST"})
     */
    public function vote(Request $request, AnswersRepository $answersRepository, EntityManagerInterface $entityManager, Poll $poll, $id): Response
    {
        $pollVote = $entityManager->getRepository(Poll::class)->find($id);
        $type = $poll->getMultipleChoice();

        $form = $this->createForm(VoteType::class, null, [
            'content' => $pollVote->getAnswer(),
            'type' => $poll->getMultipleChoice(),
        ]);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            if($type === true){
                $select = $form['content']->getData();

                foreach ($select as $selectContent){
                    $selectContent->setVoteCount( $selectContent->getVoteCount()+1 );
                    $entityManager = $this->getDoctrine()->getManager();
                    $entityManager->persist($selectContent);
                }
            } else {
                $select = $form['content']->getData();
                $select->setVoteCount( $select->getVoteCount()+1 );

                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->persist($select);
            }

            $entityManager->flush();
            $items = $form['content']->getData();

            return $this->redirectToRoute('poll_result', [
                'id' => $poll->getId(),
            ]);
        }

        return $this->render('poll/vote.html.twig', [
            'voteForm' => $form->createView(),
            'type' => $type,
            'content' => $pollVote->getAnswer(),
            'poll' => $poll,
        ]);
    }

    /**
     * @Route("/{id}/result", name="poll_result")
     */
    public function result(Poll $poll, EntityManagerInterface $entityManager, $id): Response
    {
        $pollVote = $entityManager->getRepository(Poll::class)->find($id);
        dump($pollVote);
        return $this->render('poll/result.html.twig', [
            'poll' => $poll,
            'content' => $pollVote->getAnswer(),
        ]);
    }


//    /**
//     * @Route("/{id}/edit", name="poll_edit", methods={"GET","POST"})
//     */
//    public function edit(Request $request, Poll $poll): Response
//    {
//        $form = $this->createForm(PollType::class, $poll);
//        $form->handleRequest($request);
//
//        if ($form->isSubmitted() && $form->isValid()) {
//            $this->getDoctrine()->getManager()->flush();
//
//            return $this->redirectToRoute('poll_result');
//        }
//
//        return $this->render('poll/edit.html.twig', [
//            'poll' => $poll,
//            'form' => $form->createView(),
//        ]);
//    }
}

templates/poll/_delete_form.html.twig
<form method="post" action="{{ path('poll_delete', {'id': poll.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ poll.id) }}">
    <button class="btn">Delete</button>
</form>

templates/poll/_form.html.twig
{{ form_start(form) }}
    <div class="form-header">
        <div class="title">
            {{ form_label(form.title) }}
            {{ form_errors(form.title) }}
            {{ form_widget(form.title) }}
        </div>
    </div>

   <div class="form-body">
       <div class="answer">
           {{ form_label(form.answer) }}
           {{ form_errors(form.answer) }}
           {{ form_widget(form.answer) }}
       </div>

       <div class="large-7 cell base-checkbox">
           <div class="multiple_choise">
               {{ form_label(form.multiple_choice) }}
               {{ form_errors(form.multiple_choice) }}
               {{ form_widget(form.multiple_choice) }}
           </div>

          {# <div class="draft">
               {{ form_label(form.draft) }}
               {{ form_errors(form.draft) }}
               {{ form_widget(form.draft) }}
           </div>#}
       </div>

       <button type="button" class="add-another-collection-widget button small shadow" data-list-selector="#email-fields-list">{{ 'create.add_choice'|trans() }}</button>

       <button class="btnsave alert button small expanded shadow">{{ 'create.save'|trans() }}</button>
   </div>
{{ form_end(form) }}

templates/poll/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Poll{% endblock %}

{% block body %}
    <h1>Edit Poll</h1>

    {{ include('poll/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('poll_index') }}">back to list</a>

    {{ include('poll/_delete_form.html.twig') }}
{% endblock %}

templates/poll/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Poll index{% endblock %}

{% block body %}
    <h1>Poll index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Multiple_choice</th>
                <th>Draft</th>
                <th>Date</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for poll in polls %}
            <tr>
                <td>{{ poll.id }}</td>
                <td>{{ poll.title }}</td>
                <td>{{ poll.multipleChoice ? 'Yes' : 'No' }}</td>
                <td>{{ poll.draft ? 'Yes' : 'No' }}</td>
                <td>{{ poll.date ? poll.date|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('poll_show', {'id': poll.id}) }}">show</a>
                    <a href="{{ path('poll_edit', {'id': poll.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('poll_new') }}">Create new</a>
{% endblock %}

templates/poll/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'create.strawpoll'|trans() }}{% endblock %}

{% block body %}
    <div class="strawpoll-container">
        <div class="strawpoll-wrapper">

            <div class="strawpoll-content">
                <header>
                    {{ include('poll/_form.html.twig') }}
                </header>
            </div>

        </div>
    </div>
{% endblock %}

templates/poll/result.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ poll.title }}{% endblock %}

{% block body %}
    {{ poll.title }}

    {% for content in poll.answer %}
        <div>{{ content.content }}{{ content.voteCount }}</div>
    {% endfor %}
{% endblock %}

templates/poll/vote.html.twig
{% extends 'base.html.twig' %}

{% block title %}. {% endblock %}

{% block body %}



    <div class="strawpoll-container">
        <div class="strawpoll-wrapper">

            <div class="strawpoll-content">
                <header class="vote-header">
                    {{ poll.title }}
                </header>
                <div class="vote-body">
                    {{ form_start(voteForm) }}
                    {% for content in voteForm.content %}
                        <div>{{ form_widget(content) }}{{ form_label(content) }}</div>
                    {% endfor %}
                    {{ form_rest(voteForm) }}
                    <input class="btnsave alert button small expanded shadow" type="submit" value="Voter">
                    {{ form_end(voteForm) }}
                </div>
            </div>

        </div>
    </div>
{% endblock %}